# Generated by Django 3.2.7 on 2022-01-22 16:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211204_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='content'),
        ),
    ]
